name: CI syntax, formating, build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.102' 

      - name: Install dotnet format tool
        run: dotnet tool install -g dotnet-format

      - name: Run dotnet format (check code formatting)
        run: dotnet format --check

      - name: Run dotnet build (syntax and compile check)
        run: dotnet build --no-restore 

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '9.0.102' 

      - name: Install dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release
